--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/wizxrdx-pm-pl/DamageIndicator
build-by-default: true
branches:
- main
projects:
  DamageIndicator:
    path: ""
    lint:
      phpstan: true
...
